### ISSUE TITLE
[JENKINS-48364] Varargs not recognized when first arg is null

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/script-security-plugin#783]
<p>After upgrading the Script Security Plugin from 1.35 to 1.36, some methods are no longer recognized as valid methods if the first parameters value is null. Find an example below. Probably related to issues <a href="https://issue-redirect.jenkins.io/issue/47893" title="GroovyCastException using script-security-plugin 1.35" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/47893">JENKINS-47893</a>"><del>JENKINS-47893</del></a> or <a href="https://issue-redirect.jenkins.io/issue/47159" title="Check for varargs in script-security plugin fails " class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/47159">JENKINS-47159</a>"><del>JENKINS-47159</del></a> fixed in version 1.36.</p>

<p> </p>

<p>I tried to downgrade the plugin from 1.36 to 1.35, and after restarting Jenkins, all pipelines broke, since there were other updated plugins depending on version 1.36. Had to stick with version 1.36 and change the method's logic to check nulls before calling the method that uses varargs.</p>

<p> </p>

<p><b><em>def printDebugMethodStart(methodName, ... parameters = null) {</em></b></p>

<p>       <em>// logic doesn't matter</em><br/>
 <b><em>}</em></b></p>

<p> </p>

<p>// This call works</p>

<p><b><em>printDebugMethodStart("myMethod", "param1", "param2", "paramn")</em></b></p>

<p> </p>

<p>// This call fails (perfectly good case, since I do have 3 parameters in this varargs, but the first parameter happens to have null value)</p>

<p><b><em>printDebugMethodStart("myMethod", <font color="#ff0000">null</font>, "param2", "paramn")</em></b></p>

<p> </p>

<p>// Error details</p>

<p>java.lang.NoSuchMethodError: No such DSL method 'printDebugMethodStart' found among steps <span class="error">&#91;archive, bat, build, catchError, checkout, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, echo, envVarsForTool, error, fileExists, findFiles, getContext, git, httpRequest, input, isUnix, junit, library, libraryResource, load, mail, milestone, nexusArtifactUploader, nexusPolicyEvaluation, nexusPublisher, node, parallel, powershell, properties, pwd, readFile, readJSON, readManifest, readMavenPom, readProperties, readTrusted, readYaml, registerWebhook, resolveScm, retry, script, sh, sha1, sleep, stage, stash, step, svn, timeout, timestamps, tm, tool, touch, unarchive, unstash, unzip, validateDeclarativePipeline, waitForQualityGate, waitForWebhook, waitUntil, withContext, withCredentials, withDockerContainer, withDockerRegistry, withDockerServer, withEnv, wrap, writeFile, writeJSON, writeMavenPom, writeYaml, ws, zip&#93;</span> or symbols <span class="error">&#91;all, allOf, always, ant, antFromApache, antOutcome, antTarget, any, anyOf, apiToken, architecture, archiveArtifacts, artifactManager, authorizationMatrix, batchFile, booleanParam, branch, buildButton, buildDiscarder, caseInsensitive, caseSensitive, certificate, changelog, changeset, choice, choiceParam, clock, cloud, command, credentials, cron, crumb, defaultView, demand, disableConcurrentBuilds, docker, dockerCert, dockerfile, downloadSettings, downstream, dumb, envVars, environment, expression, file, fileParam, filePath, fingerprint, frameOptions, freeStyle, freeStyleJob, fromScm, fromSource, git, headRegexFilter, headWildcardFilter, hyperlink, hyperlinkToModels, inheriting, inheritingGlobal, installSource, jdk, jdkInstaller, jgit, jgitapache, jnlp, jobDsl, jobName, label, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, legacy, legacySCM, list, local, location, logRotator, loggedInUsersCanDoAnything, masterBuild, maven, maven3Mojos, mavenErrors, mavenMojos, mavenWarnings, modernSCM, msbuild, msbuildError, msbuildWarning, myView, node, nodeProperties, nonInheriting, nonStoredPasswordParam, none, not, overrideIndexTriggers, paneStatus, parameters, password, pattern, pipeline-model, pipelineTriggers, plainText, plugin, pollSCM, projectNamingStrategy, proxy, queueItemAuthenticator, quietPeriod, remotingCLI, run, runParam, schedule, scmRetryCount, search, security, shell, skipDefaultCheckout, skipStagesAfterUnstable, slave, sourceRegexFilter, sourceWildcardFilter, sshUserPrivateKey, stackTrace, standard, status, string, stringParam, swapSpace, text, textParam, tmpSpace, toolLocation, unsecured, upstream, usernameColonPassword, usernamePassword, viewsTabBar, weather, withAnt, withSonarQubeEnv, zfs, zip&#93;</span> or globals <span class="error">&#91;currentBuild, docker, env, params, pipeline, scm&#93;</span><br/>
 at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:173)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)<br/>
 at sun.reflect.GeneratedMethodAccessor277.invoke(Unknown Source)<br/>
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
 at java.lang.reflect.Method.invoke(Method.java:498)<br/>
 at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)<br/>
 at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)<br/>
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)<br/>
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)<br/>
 at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)<br/>
 at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)<br/>
 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)<br/>
 at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)<br/>
 at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)<br/>
 at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:133)<br/>
 at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:120)<br/>
 at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:153)<br/>
 at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:157)<br/>
 at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:122)<br/>
 at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:127)<br/>
 at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)<br/>
 at WorkflowScript.run(WorkflowScript:52)<br/>
 at __<em>cps.transform</em>__(Native Method)<br/>
 at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)<br/>
 at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)<br/>
 at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)<br/>
 at sun.reflect.GeneratedMethodAccessor252.invoke(Unknown Source)<br/>
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
 at java.lang.reflect.Method.invoke(Method.java:498)<br/>
 at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)<br/>
 at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)<br/>
 at com.cloudbees.groovy.cps.Next.step(Next.java:83)<br/>
 at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)<br/>
 at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)<br/>
 at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)<br/>
 at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)<br/>
 at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)<br/>
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)<br/>
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:35)<br/>
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)<br/>
 at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)<br/>
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:32)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:331)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:243)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:231)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)<br/>
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>
 at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)<br/>
 at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)<br/>
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)<br/>
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<br/>
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)<br/>
 at java.lang.Thread.run(Thread.java:748)</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=acxmatos">acxmatos</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-48364" target="_blank">Varargs not recognized when first arg is null</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/abayer.png" title="abayer's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=abayer">abayer</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>component(s)</b>: script-security-plugin
<li><b>label(s)</b>: regression
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-12-11T15:20:04+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 5
<li><b>imported</b>: 2025-12-09
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading the Script Security Plugin from 1.35 to 1.36, some methods are no longer recognized as valid methods if the first parameters value is null. Find an example below. Probably related to issues <a href="https://issues.jenkins.io/browse/JENKINS-47893" title="GroovyCastException using script-security-plugin 1.35" class="issue-link" data-issue-key="JENKINS-47893"><del>JENKINS-47893</del></a> or <a href="https://issues.jenkins.io/browse/JENKINS-47159" title="Check for varargs in script-security plugin fails " class="issue-link" data-issue-key="JENKINS-47159"><del>JENKINS-47159</del></a> fixed in version 1.36.</p>

<p> </p>

<p>I tried to downgrade the plugin from 1.36 to 1.35, and after restarting Jenkins, all pipelines broke, since there were other updated plugins depending on version 1.36. Had to stick with version 1.36 and change the method's logic to check nulls before calling the method that uses varargs.</p>

<p> </p>

<p><b><em>def printDebugMethodStart(methodName, ... parameters = null) {</em></b></p>

<p>       <em>// logic doesn't matter</em>
 <b><em>}</em></b></p>

<p> </p>

<p>// This call works</p>

<p><b><em>printDebugMethodStart("myMethod", "param1", "param2", "paramn")</em></b></p>

<p> </p>

<p>// This call fails (perfectly good case, since I do have 3 parameters in this varargs, but the first parameter happens to have null value)</p>

<p><b><em>printDebugMethodStart("myMethod", <font color="#ff0000">null</font>, "param2", "paramn")</em></b></p>

<p> </p>

<p>// Error details</p>

<p>java.lang.NoSuchMethodError: No such DSL method 'printDebugMethodStart' found among steps <span class="error">&#91;archive, bat, build, catchError, checkout, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, echo, envVarsForTool, error, fileExists, findFiles, getContext, git, httpRequest, input, isUnix, junit, library, libraryResource, load, mail, milestone, nexusArtifactUploader, nexusPolicyEvaluation, nexusPublisher, node, parallel, powershell, properties, pwd, readFile, readJSON, readManifest, readMavenPom, readProperties, readTrusted, readYaml, registerWebhook, resolveScm, retry, script, sh, sha1, sleep, stage, stash, step, svn, timeout, timestamps, tm, tool, touch, unarchive, unstash, unzip, validateDeclarativePipeline, waitForQualityGate, waitForWebhook, waitUntil, withContext, withCredentials, withDockerContainer, withDockerRegistry, withDockerServer, withEnv, wrap, writeFile, writeJSON, writeMavenPom, writeYaml, ws, zip&#93;</span> or symbols <span class="error">&#91;all, allOf, always, ant, antFromApache, antOutcome, antTarget, any, anyOf, apiToken, architecture, archiveArtifacts, artifactManager, authorizationMatrix, batchFile, booleanParam, branch, buildButton, buildDiscarder, caseInsensitive, caseSensitive, certificate, changelog, changeset, choice, choiceParam, clock, cloud, command, credentials, cron, crumb, defaultView, demand, disableConcurrentBuilds, docker, dockerCert, dockerfile, downloadSettings, downstream, dumb, envVars, environment, expression, file, fileParam, filePath, fingerprint, frameOptions, freeStyle, freeStyleJob, fromScm, fromSource, git, headRegexFilter, headWildcardFilter, hyperlink, hyperlinkToModels, inheriting, inheritingGlobal, installSource, jdk, jdkInstaller, jgit, jgitapache, jnlp, jobDsl, jobName, label, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, legacy, legacySCM, list, local, location, logRotator, loggedInUsersCanDoAnything, masterBuild, maven, maven3Mojos, mavenErrors, mavenMojos, mavenWarnings, modernSCM, msbuild, msbuildError, msbuildWarning, myView, node, nodeProperties, nonInheriting, nonStoredPasswordParam, none, not, overrideIndexTriggers, paneStatus, parameters, password, pattern, pipeline-model, pipelineTriggers, plainText, plugin, pollSCM, projectNamingStrategy, proxy, queueItemAuthenticator, quietPeriod, remotingCLI, run, runParam, schedule, scmRetryCount, search, security, shell, skipDefaultCheckout, skipStagesAfterUnstable, slave, sourceRegexFilter, sourceWildcardFilter, sshUserPrivateKey, stackTrace, standard, status, string, stringParam, swapSpace, text, textParam, tmpSpace, toolLocation, unsecured, upstream, usernameColonPassword, usernamePassword, viewsTabBar, weather, withAnt, withSonarQubeEnv, zfs, zip&#93;</span> or globals <span class="error">&#91;currentBuild, docker, env, params, pipeline, scm&#93;</span>
 at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:173)
 at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)
 at sun.reflect.GeneratedMethodAccessor277.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
 at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
 at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
 at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
 at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
 at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
 at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:133)
 at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:120)
 at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:153)
 at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:157)
 at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:122)
 at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:127)
 at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
 at WorkflowScript.run(WorkflowScript:52)
 at __<em>cps.transform</em>__(Native Method)
 at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
 at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
 at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
 at sun.reflect.GeneratedMethodAccessor252.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
 at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
 at com.cloudbees.groovy.cps.Next.step(Next.java:83)
 at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
 at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
 at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
 at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
 at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:35)
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
 at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:32)
 at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:331)
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:243)
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:231)
 at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
 at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:748)</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Jenkins 2.73.3, Script Security Plugin 1.36, RedHat Release Server 7.3-7.el7.x86_64</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
- _Remote links associated with this issue:_


  - [CloudBees Internal CLTS-2531](https://cloudbees.atlassian.net/browse/CLTS-2531)
  - [PR #​168](https://github.com/jenkinsci/script-security-plugin/pull/168)

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-48364?focusedId=321768&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-321768">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I wonder whether casting null to the expected type makes a difference.</p>
</pre>
</details>

</ul>
</details>

<p>I wonder whether casting null to the expected type makes a difference.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/abayer.png" title="abayer's avatar" /> abayer:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-48364?focusedId=321776&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-321776">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Found the problem - our type checking for whether something's a valid varargs case looks at the first parameter after the "fixed" parameters and checks if it's an instance of the varargs component type before proceeding. <tt>null</tt>, strangely enough, is not an instance of any type. =) So in the PR at <a href="https://github.com/jenkinsci/script-security-plugin/pull/168" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/script-security-plugin/pull/168</a>, I've added special-casing for <tt>null</tt>.</p>
</pre>
</details>

</ul>
</details>

<p>Found the problem - our type checking for whether something's a valid varargs case looks at the first parameter after the "fixed" parameters and checks if it's an instance of the varargs component type before proceeding. <tt>null</tt>, strangely enough, is not an instance of any type. =) So in the PR at <a href="https://github.com/jenkinsci/script-security-plugin/pull/168" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/script-security-plugin/pull/168</a>, I've added special-casing for <tt>null</tt>.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/scm_issue_link.png" title="scm_issue_link's avatar" /> scm_issue_link:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-48364?focusedId=322388&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-322388">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Code changed in jenkins
User: Andrew Bayer
Path:
 src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java
 src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java
<a href="http://jenkins-ci.org/commit/script-security-plugin/deda81c27a88cecf92077e1666374a9b6abeb0ef" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/script-security-plugin/deda81c27a88cecf92077e1666374a9b6abeb0ef</a>
Log:
  <span class="error">&#91;FIXED JENKINS-48364&#93;</span> Treat null first vararg param properly.</p>


</pre>
</details>

</ul>
</details>

<p>Code changed in jenkins<br/>
User: Andrew Bayer<br/>
Path:<br/>
 src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/GroovyCallSiteSelector.java<br/>
 src/test/java/org/jenkinsci/plugins/scriptsecurity/sandbox/groovy/SandboxInterceptorTest.java<br/>
<a href="http://jenkins-ci.org/commit/script-security-plugin/deda81c27a88cecf92077e1666374a9b6abeb0ef" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/script-security-plugin/deda81c27a88cecf92077e1666374a9b6abeb0ef</a><br/>
Log:<br/>
  <span class="error">&#91;FIXED <a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/48364">JENKINS-48364</a>&#93;</span> Treat null first vararg param properly.</p>
